# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 789)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/simge/driver.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("* {\n"
"    font-family: \"Segoe UI\", sans-serif;\n"
"    font-size: 12pt;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* Genel pencere arka planı */\n"
"QMainWindow, QWidget {\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"/* QLabel */\n"
"QLabel {\n"
"    color: #f0f0f0;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"/* QPushButton */\n"
"QPushButton {\n"
"    background-color: #1e1e1e;\n"
"    color: white;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2d2d2d;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #0078d7;\n"
"}\n"
"\n"
"/* QLineEdit */\n"
"QLineEdit {\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    border: 1px solid #3a3a3a;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* QGroupBox */\n"
"QGroupBox {\n"
"    background-color: #737272;\n"
"    border: 1px solid #9e0b0b;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    font-size: 7pt;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 0px;\n"
"    padding: 0 23px 0 23px;\n"
"    \n"
"}\n"
"\n"
"/* ScrollArea */\n"
"QScrollArea {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollArea QWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Scrollbar Dikey */\n"
"QScrollBar:vertical {\n"
"    background: #1e1e1e;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #555;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #888;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"/* Scrollbar Yatay */\n"
"QScrollBar:horizontal {\n"
"    background: #1e1e1e;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    border: none;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #555;\n"
"    min-width: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #888;\n"
"}\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 0px;\n"
"}\n"
"\n"
"/* QComboBox */\n"
"QComboBox {\n"
"    background-color: #1a1a1a;\n"
"    border: 1px solid #3a3a3a;\n"
"    padding: 5px;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2a2a2a;\n"
"    selection-background-color: #0078d7;\n"
"}\n"
"\n"
"/* QCheckBox */\n"
"QCheckBox {\n"
"    spacing: 5px;\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #0078d7;\n"
"    border: 1px solid #ffffff;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #333;\n"
"    border: 1px solid #aaa;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: #2a2a2a;  /* Arka plan */\n"
"    color: white;               /* Yazı rengi */\n"
"    border: 1px solid #910181;      /* Kenarlık */\n"
"    padding: 5px;\n"
"    border-radius: 4px;\n"
"    font-size: 10pt;\n"
"    font-family: Consolas;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QPushButton {\n"
"    background-color: #35bd0f;\n"
"    border-radius: 25%;\n"
"    min-width: 10px;\n"
"    min-height: 10px;\n"
"}\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 941, 700))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.startmic = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.startmic.setMinimumSize(QtCore.QSize(95, 95))
        self.startmic.setMaximumSize(QtCore.QSize(82, 82))
        self.startmic.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"}")
        self.startmic.setAlignment(QtCore.Qt.AlignCenter)
        self.startmic.setObjectName("startmic")
        self.StartMic_Button = QtWidgets.QPushButton(self.startmic)
        self.StartMic_Button.setGeometry(QtCore.QRect(10, 30, 72, 50))
        self.StartMic_Button.setMinimumSize(QtCore.QSize(36, 24))
        self.StartMic_Button.setStyleSheet("QPushButton {\n"
"    background-color: #35bd0f;\n"
"    border-radius: 25%;\n"
"    min-width: 10px;\n"
"    min-height: 10px;\n"
"}")
        self.StartMic_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/simge/mic_111082.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartMic_Button.setIcon(icon1)
        self.StartMic_Button.setIconSize(QtCore.QSize(30, 30))
        self.StartMic_Button.setObjectName("StartMic_Button")
        self.gridLayout_4.addWidget(self.startmic, 2, 2, 1, 1)
        self.Komut_bilgisi = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Komut_bilgisi.setAlignment(QtCore.Qt.AlignCenter)
        self.Komut_bilgisi.setObjectName("Komut_bilgisi")
        self.gridLayout_4.addWidget(self.Komut_bilgisi, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: #737272;\n"
"    border: 2px solid #9e0b0b;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    font-size: 7pt;\n"
"\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: #292929;\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_3.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: #737272;\n"
"    border: 2px solid #9e0b0b;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    font-size: 7pt;\n"
"\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Bluetooth_durum_2 = QtWidgets.QLabel(self.groupBox_3)
        self.Bluetooth_durum_2.setObjectName("Bluetooth_durum_2")
        self.gridLayout_5.addWidget(self.Bluetooth_durum_2, 0, 1, 1, 1)
        self.Bluetooth_durum = QtWidgets.QLabel(self.groupBox_3)
        self.Bluetooth_durum.setObjectName("Bluetooth_durum")
        self.gridLayout_5.addWidget(self.Bluetooth_durum, 0, 0, 1, 1)
        self.Bluetooth_durum_3 = QtWidgets.QLabel(self.groupBox_3)
        self.Bluetooth_durum_3.setObjectName("Bluetooth_durum_3")
        self.gridLayout_5.addWidget(self.Bluetooth_durum_3, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: #737272;\n"
"    border: 2px solid #9e0b0b;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"    font-size: 7pt;\n"
"\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: #292929;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 1, 0, 1, 1)
        self.startgrp = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.startgrp.setMinimumSize(QtCore.QSize(95, 95))
        self.startgrp.setMaximumSize(QtCore.QSize(82, 82))
        self.startgrp.setStyleSheet("QGroupBox {\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 0px;\n"
"    padding: 0 8px 0 8px;\n"
"    \n"
"}")
        self.startgrp.setAlignment(QtCore.Qt.AlignCenter)
        self.startgrp.setObjectName("startgrp")
        self.StartCar_Button = QtWidgets.QPushButton(self.startgrp)
        self.StartCar_Button.setGeometry(QtCore.QRect(10, 30, 72, 50))
        self.StartCar_Button.setMinimumSize(QtCore.QSize(36, 24))
        self.StartCar_Button.setStyleSheet("QPushButton {\n"
"    background-color: #35bd0f;\n"
"    border-radius: 25%;\n"
"    min-width: 10px;\n"
"    min-height: 10px;\n"
"}")
        self.StartCar_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/simge/restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StartCar_Button.setIcon(icon2)
        self.StartCar_Button.setIconSize(QtCore.QSize(30, 30))
        self.StartCar_Button.setObjectName("StartCar_Button")
        self.gridLayout_4.addWidget(self.startgrp, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 4, 1, 1)
        self.Tarih = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.Tarih.setAlignment(QtCore.Qt.AlignCenter)
        self.Tarih.setObjectName("Tarih")
        self.gridLayout_4.addWidget(self.Tarih, 2, 4, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startmic.setTitle(_translate("MainWindow", "Konuş"))
        self.Komut_bilgisi.setText(_translate("MainWindow", "Hali Hazırda\n"
"Gerçekleştirilen Komut"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Araç Durumu</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Araç Durumu"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Alınan Komutlar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Bağlantılar"))
        self.Bluetooth_durum_2.setText(_translate("MainWindow", "Durum"))
        self.Bluetooth_durum.setText(_translate("MainWindow", "Bluetooth:"))
        self.Bluetooth_durum_3.setText(_translate("MainWindow", "Durum"))
        self.groupBox.setTitle(_translate("MainWindow", "Tamamlanan Komutlar"))
        self.startgrp.setTitle(_translate("MainWindow", "Aracı Çalıştır"))
        self.label.setText(_translate("MainWindow", "Alınan ses komutu"))
        self.Tarih.setText(_translate("MainWindow", "Tarih"))
import simge_rc
